inicio
    real n1, n2
    
    escrever "Escreva o primeiro numero: "
    ler n1
    escrever "Escreva o segundo numero: "
    ler n2
    
    se n1 > n2 entao
        escrever "O numero " , n1 , " é o maior numero."
    senao
        se n2 > n1 entao
            escrever "O numero " , n2 , " é o maior numero."
        senao
            escrever "Os dois numeros são iguais."
        fimse
    fimse
fim

